### ISSUE TITLE
Update class controller error: findone is not a function

### ISSUE THREAD

**Issue by krabbi** [manishkatyan/bbb-strapi#62]
https://github.com/manishkatyan/bbb-strapi/blob/15221296844eb7809bd771fea2f45ade2c6162ca/server/controllers/classController.js#L56

`findone` is not a function

Require change to update
```
    const res = await strapi
      .query('plugin::bigbluebutton.class')
      .update({
        where: {
          id,
        },
        data: ctx.request.body,
    });
```

**Comment by nishekh-e-r** [comment]
@krabbi we haven't added a feature to update class will add it in the future.
