### ISSUE TITLE
Question: Integration with user-permissions

### ISSUE THREAD

**Issue by shubhendumadhukar** [manishkatyan/bbb-strapi#65]
Is there a way to restrict access to api endpoints based on user's role? Any documentation would be helpful.

**Comment by nishekh-e-r** [comment]
Hi @shubhendumadhukar 
we are checking on it. Will update you soon.

**Comment by nishekh-e-r** [comment]
@shubhendumadhukar can you tell me your use case?
what problem you are trying to solve?
